version: '3.6'

services:

  vault:
    container_name: vault.server
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
  envconsul:
    container_name: envconsul.server
    build:
      context: ./envconsul
      dockerfile: Dockerfile
    environment:
      - VAULT_ADDR=http://${HOST_IP}:8200
      #not root token, but what with specific ACL's.
      - VAULT_TOKEN=88503e0c-d3ca-e344-fd24-57fab7a31f49
    command: tail -F
